name: benchmark

on:
  workflow_dispatch:
    inputs:
      run_parser:
        description: 'Run parser benchmark'
        required: false
        type: boolean
        default: true
      run_executor:
        description: 'Run executor benchmark'
        required: false
        type: boolean
        default: true
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      parser: ${{ steps.filter.outputs.parser }}
      executor: ${{ steps.filter.outputs.executor }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            parser:
              - 'viviscript-core/src/parser.rs'
              - 'viviscript-core/src/lexer.rs'
              - 'viviscript-core/benches/parse_bench.rs'
            executor:
              - 'viviscript-core/src/executor/**'
              - 'viviscript-core/benches/executor_bench.rs'

  bench:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - bench: parse_bench
            run: |
              ${{ needs.detect-changes.outputs.parser == 'true' ||
                  github.event.inputs.run_parser == 'true' }}
          - bench: executor_bench
            run: |
              ${{ needs.detect-changes.outputs.executor == 'true' ||
                  github.event.inputs.run_executor == 'true' }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Cache benchmark baseline
        uses: actions/cache@v4
        with:
          path: ./target/criterion
          key: criterion-baseline-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            criterion-baseline-${{ runner.os }}-

      - name: Run ${{ matrix.bench }}
        if: matrix.run == true
        run: cargo bench --bench ${{ matrix.bench }}

      - name: Deploy Criterion report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion/
          destination_dir: criterion
          keep_files: true